local_govt_area = {

    'Abuja': ['Abaj', 'Abaji', 'Abuja+Municipal', 'Bwari', 'Gwagwalada', 'Kuje',
              'Kwali', 'Municipal+Area+Council'],
    'Abia': ['Aba+North', 'Aba+North', 'Aba+South', 'Arochukwu', 'Bende', 'Bende',
             'Ikwuano', 'Ikwuano', 'Isiala', 'Isiala+Ngwa+North', 'Isiala+Ngwa+South',
             'Isiala+Ngwa+South', 'Isuikwuato', 'Isukwuato', 'Ngwa+North', 'Obi+Ngwa',
             'Ohafia', 'Osisioma', 'Ugwunagbo', 'Ukwa+East', 'Ukwa+East', 'Ukwa+West',
             'Ukwa+West', 'Umu+Nneochi', 'Umuahia', 'Umuahia+North', 'Umuahia+South'],
    'Adamawa': ['Hung', 'Demsa', 'Fufore', 'Fufure', 'Ganye', 'Gayuk', 'Girei', 'Gombi',
                'Grie', 'Hong', 'Jada', 'Jimeta', 'Lamurde', 'Madagali', 'Maiha',
                'Mayo+Belwa', 'Michika', 'Mubi+North', 'Mubi+South', 'Numan', 'Numna',
                'Shelleng', 'Song', 'Toungo', 'Yola+North', 'Yola+North', 'Yola+South'],
    'Akwa+Ibom': ['Abak', 'Eastern+Obolo', 'Eket', 'Esit+Eket', 'Essien+Udim', 'Etim+Ekpo',
                  'Etimekpo', 'Etinan', 'Ibeno', 'Ibesikpo+Asutan', 'Ibiono+lbom', 'Ika',
                  'Ikono', 'Ikot+Abasi', 'Ikot+Ekpene', 'Ini', 'Itu', 'lkot+Abasi',
                  'Mbo', 'Mkpat+Enin', 'Nsit', 'Nsit+lbom', 'Nsit-Atai', 'Nsit-Ubium',
                  'Obot+Akara', 'Okobo', 'Onna', 'Oron', 'Oruk+Anam', 'Oruko+Ete',
                  'Ubium', 'Udung', 'Udung+Uko', 'Ukanafun', 'Uko', 'Uruan',
                  'Urue+Offoung', 'Uyo', 'Oruko'],
    'Anambra': ['Aguata', 'Anambra', 'Anambra+East', 'Anambra+West', 'Anaocha',
                'Awka+North', 'Awka+South', 'Ayamelum', 'Dunukofia', 'Ekwusigo',
                'Idemili+North', 'Idemili+South', 'Ihiala', 'Njikoka', 'Nnewi+North',
                'Nnewi+South', 'Ogbaru', 'Onitsha+North', 'Onitsha+South', 'Orumba+North',
                'Orumba+South', 'Oyi'],
    'Bauchi': ['Alkaleri', 'Ganjuwa', 'hira', 'Bauchi', 'Giade', 'Tafawa+Balewa',
               'Bogoro', 'Jama+are', 'Itas+gadau', 'Darazo', 'Katagum', 'Toro', 'Dass',
               'Kirfi', 'Warji', 'Gamawa', 'Misau', 'Zaki', 'Ningi', 'Dambam', 'Damban',
               'Itas', 'Jamaare', 'Shira', 'Gadau'],
    'Bayelsa': ['Brass', 'Ekeremor', 'Kolok', 'Kolokuma', 'Membe', 'Nembe',
                'Ogbia', 'Opokuma', 'Sagbama', 'Southern+Ijaw', 'Yenagoa'],
    'Benue': ['Ador', 'Obi', 'Ukum', 'Agatu', 'Kastina+ala', 'Ogbadibo', 'Vandekya',
              'Apa', 'Konshisha', 'Ohimini', 'Buruku', 'Kwande', 'Oju', 'Gboko', 'Logo',
              'Okpokwu', 'Guma', 'Makurdi', 'Oturkpo', 'Gwer+east', 'Tarka', 'Ado',
              'Gwer+West', 'Katsina+Ala', 'Ushongo', 'Vandeikya'],
    'Bornu': ['Abadam', 'Abadan', 'Askira', 'Balge', 'Bama', 'Bayo', 'Biu', 'Chibok',
              'Damboa', 'Dikwa', 'Dikwagubio', 'Gubio', 'Guzamala', 'Gwoza', 'Hawul',
              'Jere', 'Kaga', 'Kala', 'Kalka', 'Konduga', 'Kukawa', 'Kwaya+Kusar',
              'Kwaya+ku', 'Mafa', 'Magumeri', 'Maiduguri', 'Marte', 'Mobbar', 'Monguno',
              'Ngala', 'Nganzai', 'Shani', 'Uba'],
    'Cross+River': ['Abi', 'Akamkpa', 'Akampa', 'Akpabuyo', 'Bakassi', 'Bekwara',
                    'Bekwarra', 'Biase', 'Boki', 'Calabar+Municipal', 'Calabar+south',
                    'Etung', 'Ikom', 'Obanliku', 'Obubra', 'Obudu', 'Odukpani', 'Ogoja',
                    'Ugep+north', 'Yakuur', 'Yala', 'Yarkur'],
    'Delta': ['Aniocha+North', 'Aniocha+south', 'Anioha', 'Bomadi', 'Burutu',
              'Ethiope+east', 'Ethiope+west', 'Ika+north+east', 'Ika+south', 'Isoko+north',
              'Isoko+south', 'Ndokwa+east', 'Ndokwa+west', 'Okpe', 'Oshimili+north',
              'Oshimili+south', 'Patani', 'Sapele', 'Udu', 'Ughelli+north', 'Ughelli+south',
              'Ukwuani', 'Uviwie', 'Uvwie', 'Warri+central', 'Warri+north', 'Warri+south',
              'Warri+South+West'],
    'Ebonyi': ['Abakaliki', 'Afikpo+north', 'Afikpo+south', 'Ebonyi', 'Edda', 'Ezza',
               'Ezza+North', 'Ezza+south', 'Ikwo', 'Ishielu', 'Ivo', 'Izzi', 'Ohaozara',
               'Ohaukwu', 'Onicha'],
    'Edo': ['Akoko+Edo', 'Egor', 'Esan+central', 'Esan+North-East', 'Esan+south+east',
            'Esan+west', 'Etsako', 'Etsako+central', 'Etsako+east', 'Etsako+West',
            'Igueben', 'Ikpoba+Okha', 'Ivia+north', 'Oredo', 'Orhionmwon', 'Orhionwon',
            'Ovia+North-East', 'Ovia+south+west', 'Owan+East', 'Owan+south', 'Owan+west',
            'Uhunmwonde', 'Uhunwonde'],
    'Ekiti': ['Osi', 'Ado+Ekiti', 'Aiyekire', 'Effon+Alaiye', 'Efon', 'Ekiti+east',
              'Ekiti+south+west', 'Ekiti+west', 'Emure', 'Emure', 'Gbonyin', 'Ido',
              'Ido+Osi', 'Ijero', 'Ikere', 'Ikole', 'Ilejemeje', 'Irepodun', 'Ise',
              'ljero', 'llejemejeIrepodun', 'Moba', 'Orun', 'Oye', 'Ifelodun'],
    'Enugu': ['Aninri', 'Awgu', 'Enugu+east', 'Enugu+north', 'Enugu+south', 'Ezeagu',
              'Igbi+etiti', 'Igbo+Etiti', 'Igbo+Eze+north', 'Igbo+Eze+South', 'Isi+Uzo',
              'Nkanu+East', 'Nkanu+West', 'Nsukka', 'Oji+river', 'Udenu', 'Udi', 'Undenu',
              'Uzo+Uwani'],
    'Gombe': ['Akko', 'Bajoga', 'Balanga', 'Biliri', 'Billiri', 'Deba', 'Dukku', 'Dunakaye',
              'Funakaye', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shomgom', 'Shongom', 'Yamaltu'],
    'Imo': ['Aboh+Mbaise', 'Aguta', 'Ahiazu+Mbaise', 'Ehime+Mbano', 'Ezinhite', 'Ezinihitte',
            'Ideato+North', 'Ideato+south', 'Ihitte', 'Ikeduru', 'Isiala', 'Isiala+Mbano', 'Isu',
            'Mbaitoli', 'Ngor+Okpala', 'Njaba', 'Nkwere+Obowo', 'Nkwerre', 'Nwangele', 'Obowo',
            'Oguta', 'Ohaji+Egbema', 'Egbema', 'Okigwe', 'Onuimo', 'Orlu', 'Orsu', 'Oru', 'Oru+East',
            'Oru+west', 'Owerri', 'Owerri+Municipal', 'Owerri+North', 'Owerri+south', 'Owerri+West',
            'Uboma', 'Unuimo'],
    'Jigawa': ['Auyo', 'Babura', 'Biriniwa', 'Birnin+Kudu', 'Birnin+magaji', 'Birniwa', 'Buijiį',
               'Buji', 'Dute', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa',
               'Hadeji', 'Hadejia', 'Jahun', 'Kafin+Hausa', 'kaugama', 'Kazaure', 'Kiri+Kasama',
               'Kirikisamma', 'Kiyawa', 'Maigatari', 'Malam+Madori', 'Malamaduri', 'Miga', 'Ringim',
               'Roni', 'Sule+Tankarka', 'Sule+Tankarkar', 'Taura', 'Yankwashi'],
    'Kaduna': ['Birnin+Gwari', 'Brnin+Gwari', 'Chikun', 'Chukun', 'Giwa', 'Igabi', 'Ikara', 'Jaba',
               'Jemaa', 'Kabau', 'Kachia', 'Kaduna+North', 'Kaduna+south', 'Kagarko', 'Kagarok',
               'Kajuru', 'Kaura', 'Kauru', 'Kere', 'Kubau', 'Kudan', 'Lere', 'Makarfi',
               'Sabon+Gari', 'Sabongari', 'Sanga', 'Soba', 'Zangon+Kataf', 'Zaria', 'Jema'],
    'Kano': ['Kunch', 'Kura', 'Ajigi', 'Ajingi', 'Albasu', 'Bagwai', 'Bebeji', 'Bichi',
             'Bunkure', 'Dala', 'Dambatta', 'Dawakin+kudu', 'Dawakin+tofa', 'doguwa',
             'Fagge', 'Gabasawa', 'Garko', 'Garun+mallam', 'Gaya', 'Gezawa', 'Gwale',
             'Gwarzo', 'Kabo', 'Kano', 'Kano+Municipal', 'Karay', 'Karaye', 'Kibiya', 'Kiru',
             'Kumbotso', 'Kumbtso', 'Kunchi', 'Kura', 'Madobi', 'Maidobi', 'Makoda', 'Minjibir',
             'MInjibir+Nassarawa', 'Nasarawa', 'Rano', 'Rimin+gado', 'Rogo', 'Shanono', 'Sumaila',
             'Takai', 'Tarauni', 'Tofa', 'Tsanyawa', 'Tudun+Wada', 'Tudun+wada', 'Ungogo', 'Warawa',
             'Wudil'],
    'Katsina': ['Bakori', 'Batagarawa', 'Batsari', 'Baure', 'Bindawa', 'Charanchi', 'Dan+Musa',
                'Dandume', 'Danja', 'Dan-Musa', 'Daura', 'Dutsi', 'Dutsin+Ma', 'Faskar',
                'Faskari', 'Funtua', 'Furfi', 'Ingawa', 'Jibia', 'Jibiya', 'Kafur', 'Kaita',
                'Kankara', 'Kankia', 'Kankiya', 'Katsina', 'Kurfi', 'Kusada', 'KusadaMai+aduwa',
                'Mai+Adua', 'Malumfashi', 'Mani', 'Mash', 'Mashi', 'Matazu', 'Musawa', 'Rimi',
                'Sabuwa', 'Safana', 'Sandamu', 'Zango', 'MaiAdua'],
    'Kebbi': ['Aleiro', 'Aliero', 'Arewa+Dandi', 'Argungu', 'Augie', 'Bagudo', 'Birnin+Kebbi',
              'Bunza', 'Dandi', 'Danko', 'Fakai', 'Gwandu', 'Jeda', 'Jega', 'Kalgo', 'Koko',
              'Koko+besse', 'Maiyaama', 'Maiyama', 'Ngaski', 'Sakaba', 'Shanga', 'Suru', 'Wasugu',
              'Yauri', 'Zuru', 'Besse'],
    'Kogi': ['Adavi', 'Ajaokuta', 'Ankpa', 'Bassa', 'Dekina', 'Ibaji', 'idah', 'Igalamela',
             'Igalamela+Odolu', 'Ijumu', 'Kabba+bunu', 'Kabba', 'Kogi', 'lbaji', 'ljumu',
             'Lokoja', 'Mopa+muro', 'Ofu', 'Ogori+magongo', 'Ogori', 'Okehi', 'Okene', 'Olamaboro',
             'Omala', 'Yagba+east', 'Yagba+west', 'Bunu', 'Magongo'],
    'Kwara': ['Asa', 'Baruten', 'Ede', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin+East', 'Ilorin+south',
              'Ilorin+West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke+ero', 'Oyun',
              'Pategi'],
    'Lagos': ['Ikorodu', 'Agege', 'Alimosho', 'Alimosho+lfelodun', 'Amuwo+Odofin', 'Apapa',
              'Badagry', 'Ejigbo', 'Epe', 'Eti+Osa', 'ljaye', 'fako', 'Ibeju+Lekki',
              'Ifako+Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe', 'Lagos+Island', 'Lagos+Mainland',
              'lIbeju+Lekki', 'Mushin', 'Ojo', 'Oshodi+-Isolo', 'Shomolu', 'Surulere'],
    'Nasarawa': ['Akwanga', 'Awe', 'Doma', 'Karu', 'Keana', 'Keffi', 'Kokona', 'Lafia',
                 'Nasarawa', 'Nasarawa+Egon', 'Nassarawa', 'Obi', 'Toto', 'Wamba', 'Eggon'],
    'Niger': ['Agaie', 'Agwara', 'Bida', 'Borgu', 'Bosso', 'Chanchaga', 'Chanchanga', 'Edati',
              'Gbako', 'Gurara', 'Katcha', 'Kitcha', 'Kontagora', 'Lapai', 'Lavun', 'Magama',
              'Mariga', 'Mashegu', 'Mokwa', 'Moshegu', 'Moya', 'Muya', 'Paiko', 'Paikoro',
              'Rafi', 'Rijau', 'Shiroro', 'Suleija', 'Suleja', 'Tafa', 'Tawa+Wushishi',
              'Wushishi'],
    'Ogun': ['Abeokuta+north', 'Abeokuta+south', 'Ado+Odo', 'Agbado+north', 'Agbado+south',
             'Ewekoro', 'Idarapo', 'Ifo', 'Ijebu+North+East', 'Ijebu+Ode', 'Ikenne', 'Imeko+afon',
             'Ipokia', 'jebu+north', 'ljebu+east', 'owode', 'lkenne', 'llugun+Alaro',
             'Obafemi+Owode', 'Obafemi', 'Odeda', 'Odogbolu', 'Ogun+waterside', 'Remo+North',
             'Sagamu', 'Shagamu', 'Yewa+North', 'Yewa+South', 'Ota', 'otta'],
    'Ondo': ['Akoko+north', 'Akoko+north+east', 'Akoko+North-West', 'Akoko+south', 'Akoko+south+east',
             'Akoko+South-West', 'Akure', 'Akure+north', 'Akure+South', 'Ese+odo', 'Idanre',
             'Ifedore', 'Ilaje', 'Okeigbo', 'Ile+Oluji', 'Irele', 'laje+oke-igbo', 'llaje', 'Odigbo',
             'Okitipupa', 'Ondo', 'Ondo+east', 'Ondo+West', 'Ose', 'Owo'],
    'Osun': ['Aiyedaade', 'Aiyedire', 'Atakumosa+east', 'Atakumosa+west', 'Ayeda+ade', 'Ayedire',
             'Bolawaduro', 'Boluwaduro', 'Boripe', 'Ede', 'Ede+north', 'Ede+South', 'Egbedore',
             'Ejigbo', 'Ife+central', 'Ife+east', 'Ife+north', 'Ife+south', 'Ifedayo', 'Ifelodun',
             'Ila', 'Ilesa+East', 'Ilesa+West', 'Ilesah+east', 'Irepodun', 'Irewole', 'Isokan', 'Iwo',
             'lla+orangun', 'llesha+west', 'Obokun', 'Odo+Otin', 'Odo-otin', 'ola+oluwa', 'olorunda',
             'Oriade', 'Orolu', 'Osogbo'],
    'Oyo': ['Afijio', 'Akinyele', 'Atiba', 'Atigbo', 'Atisbo', 'Attba', 'Egbeda', 'Ibadan+central',
            'Ibadan+North', 'Ibadan+north+east', 'Ibadan+North-West', 'Ibadan+south+east',
            'Ibadan+South-West', 'Ibarapa+Central', 'Ibarapa+East', 'Ibarapa+north', 'Ido',
            'Ifedapo', 'Ifeloju', 'Irepo', 'Iseyin', 'Itesiwaju', 'Iwajowa', 'Kajola', 'Lagelu',
            'lseyin', 'lwajowa', 'lwajowa+olorunshogo', 'Ogbomosho+north', 'Ogbomosho+south',
            'Ogo+oluwa', 'Olorunsogo', 'Oluyole', 'Ona+ara', 'Ore+lope', 'Orelope', 'Ori+Ire',
            'Orire', 'Oyo', 'Oyo+east', 'Oyo+west', 'Saki+east', 'Saki+west', 'Surulere'],
    'Plateau': ['Barkin+Ladi', 'Barkin', 'Bassa', 'Bokkos', 'Jos+east', 'Jos+north', 'Jos+south',
                'Kanam', 'Kanke', 'kiyom', 'Langtang+north', 'Langtang+south', 'Mangu', 'Mikang',
                'Pankshin', 'Quaan+pan', 'Riyom', 'Shendam', 'Wase', 'ladi'],
    'Rivers': ['Odial', 'Abua', 'Ahoada+East', 'Ahoada+west', 'Akuku+toru', 'Andoni',
               'Asari+toru', 'Akpor', 'Edoni', 'Bonny', 'Degema', 'Eleme', 'Emohua', 'Emuoha',
               'Etche', 'Gokana', 'Ikwerre', 'Khana', 'Obio', 'Ogba+east', 'Ogba', 'Ogu', 'Okrika',
               'Omuma', 'Omumma', 'Opobo', 'Oyigbo', 'Port+Harcourt', 'Portharcourt', 'Tai', 'yigbo',
               'Odual', 'Egbema', 'Ndoni', 'bolo', 'Nkoro'],
    'Sokoto': ['Binji', 'Bodinga', 'Dange+Shuni', 'Dange', 'Gada', 'Goronyo', 'Gudu',
               'Gwadabawa', 'Ilella', 'Illela', 'Isa', 'Kebbe', 'Kware', 'Rabah', 'Sabon+Birni',
               'Shagari', 'Silame', 'Sokoto+north', 'Sokoto+south', 'Tambuwal', 'Tangaza', 'Tureta',
               'Wamakko', 'Wamako', 'Wurno', 'Yabo', 'shuni'],
    'Taraba': ['Akdo+kola', 'Ardo+Kola', 'Bali', 'Donga', 'Gashaka', 'Gassol', 'Ibi', 'Jalingo',
               'K+Lamido', 'Karim+Lamido', 'Kumi', 'Kurmi', 'lan', 'Lau', 'Sardauna', 'Takum',
               'Tarum', 'Ussa', 'Wukari', 'Yorro', 'Zing'],
    'Yobe': ['Bade', 'Borsari', 'Bursari', 'Damaturu', 'Fika', 'Fune', 'G+ashua', 'Geidam', 'Gogaram',
             'Gujba', 'Gulani', 'Jakusko', 'Karasuwa', 'Machina', 'Nagere', 'Nangere', 'Nguru', 'Potiskum',
             'Tarmua', 'Tarmuwa', 'Yunusari', 'Yusufari'],
    'Zamfara': ['Anka', 'bukkuyum', 'Dungudu', 'Chafe', 'Gummi', 'Gusau', 'Isa', 'Kaura', 'Mradun',
                'Maru', 'Shinkafi', 'Talata', 'Zumi', 'Bakura', 'Birnin+Magaji', 'Bungudu', 'Kaura+Namoda',
                'Maradun', 'Talata+Mafara', 'Zurmi', 'Namoda', 'Mafara', 'Kiyaw']}